### ISSUE TITLE
How to read transient measurement voltages?

### ISSUE THREAD

**Issue by KajWiik** [cstook/LTspice.jl#5]
I am trying to read voltages from a transient simulation. I tried a naïve approach and defined '.meas Vout V(Vo)' but it did not work... How to accomplish this?

**Comment by KajWiik** [comment]
I noticed that this might be not so useful because of LTspice itself: it uses dynamic step size so e.g. FFT of the waveform is rather difficult to calculate...

**Comment by cstook** [comment]
LTspice.jl only parses the log file so it can only return results of measurements.  The voltage and current waveforms as a function of time are not available.  

I assume you have already moved on since I'm responding four months late.  Sorry about that.
