### ISSUE TITLE
basic example fails

### ISSUE THREAD

**Issue by warrendale** [cstook/LTspice.jl#6]
![Screenshot from 2019-06-12 17-34-23](https://user-images.githubusercontent.com/46302867/59387954-81fc6e80-8d38-11e9-826f-0b697219ad95.png)

Using linux + wine + LTspice 

![Screenshot from 2019-06-12 17-37-02](https://user-images.githubusercontent.com/46302867/59388065-d3a4f900-8d38-11e9-8106-882265984d4c.png)

Same error on 1.1.1.  All examples from within spice work fine.  Any ideas?

**Comment by cstook** [comment]
Sorry you are having a problem.  I don't have access to a linux computer right now, but it seems to work OK with windows and LTspice XVII(x64) May 18 2019, 11:16:30 US Pacific. 

```
Starting Julia...
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.1.1 (2019-05-16)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> [ Info: Importing Revise
julia> 

julia> using LTspice

julia> cd("C:\\Users\\Chris\\.julia\\packages\\LTspice\\BdDwC\\examples\\example 1")

julia> example1 = LTspiceSimulation("example1.asc",tempdir=true)
LTspiceSimulation:
circuit path = C:\Users\Chris\AppData\Local\Temp\jl_11D8.tmp\example1.asc

Parameters
Rload                     = 75.0

Measurements
Pload


julia> example1["Rload"] = 20.0
20.0

julia> loadpower = example1["Pload"]
0.00408163

julia> loadpower = example1(100.0)
1-element LTspice.MeasurementValuesArray{Float64,1}:
 0.00444444

julia> 
```

It also passes tests on Travis.

I'm not sure whats going on here.  Let me poke around some more.

**Comment by cstook** [comment]
It probably can't find the LTspice executable.  You can specify the location with the executablepath parameter.

For example, on my windows machine, the LTspice executable location can be specified as follows.
```
example1 = LTspiceSimulation("example1.asc",executablepath="\\Program Files\\LTC\\LTspiceXVII\\XVIIx64.exe",tempdir=true)
```

Give this a try and see if it helps.

Also, it's easier to read if you enclose code, and sample output in triple backquotes instead of a screenshot.

**Comment by warrendale** [comment]
Thanks.  It turns out it CAN find the executable.  The problem is that it is not associated with wine when being called via the julia run() function.  If I make the following change and rebuild LTspice.jl it works fine.

```
function run!(x::LTspiceSimulation, force=false)
  flush(x,force)
  if x.status.ismeasurementsdirty || force
    if x.executablepath != ""  # so travis dosen't need to load LTspice
      @static if Sys.islinux()
        drive_c = "/home/$(ENV["USER"])/.wine/drive_c"
        winecircuitpath = joinpath("C:",relpath(x.circuitpath,drive_c))
        run(`wine $(x.executablepath) -b -Run $winecircuitpath`)
      else
        run(`$(x.executablepath) -b -Run $(x.circuitpath)`)
      end
    end
    parselog!(x)
    x.status.ismeasurementsdirty = false
  end
end
```

**Comment by cstook** [comment]
Thanks for fixing my code!  I'll update the code on GitHub.
