### ISSUE TITLE
OSX support

### ISSUE THREAD

**Issue by asinghvi17** [cstook/LTspice.jl#8]
Is there anything that can be done to support OSX?  The README says that it's unsupported, and while I can read LTSpice files, simulation causes Julia to hang until interrupted.

**Comment by cstook** [comment]
The OSX version of LTSpice did not support the batch command line option when this module was created, so it was not possible to support OSX.  I no longer have a mac, so I can not check if Analog Devices has added the feature, or work on developing anything mac specific.

**Comment by dnadlinger** [comment]
The `-b` option seems to enable batch mode on macOS as well, although I can't find any documentation on it.

**Comment by cstook** [comment]
I don't think there is anything is the code preventing it from running on macOS other than the lack of support of batch mode option, so if -b -Run is now supported it might just work.

LTspice command line switches are documented here http://ltwiki.or/index.php?title=Command_Line_Switches
The LTspice users group has moved to groups.io https://groups.io/g/LTspice

If this works now, let me know and I'll update the readme.
