### ISSUE TITLE
Support for .MEAS AC simulations

### ISSUE THREAD

**Issue by EliMattingly22** [cstook/LTspice.jl#9]
It seems that measuring ac analysis isn't (well or at all) supported. For example, a simple LRC circuit's .asc file is below:
Version 4
SHEET 1 1020 680
WIRE 80 48 -48 48
WIRE 144 48 80 48
WIRE 256 48 224 48
WIRE 256 80 256 48
WIRE 256 208 256 144
WIRE -48 272 -48 48
WIRE 256 288 256 272
WIRE 256 304 256 288
FLAG 256 304 0
FLAG -48 352 0
FLAG 80 128 0
DATAFLAG 32 48 ""
DATAFLAG 256 176 ""
DATAFLAG -48 224 ""
SYMBOL res -64 256 R0
SYMATTR InstName R2
SYMATTR Value 2
SYMBOL voltage 256 192 R0
WINDOW 123 24 124 Left 2
WINDOW 39 0 0 Left 0
SYMATTR Value2 AC 1
SYMATTR InstName V2
SYMATTR Value 1
SYMBOL cap 240 80 R0
SYMATTR InstName C1
SYMATTR Value 100m
SYMBOL ind 64 32 R0
SYMATTR InstName L1
SYMATTR Value {LVal}
SYMBOL res 240 32 R90
WINDOW 0 0 56 VBottom 2
WINDOW 3 32 56 VTop 2
SYMATTR InstName R1
SYMATTR Value 1m
TEXT 328 136 Left 2 !.op
TEXT 472 104 Left 2 !.ac lin 1000 1 100
TEXT 456 152 Left 2 !.param LVal = .01\n.meas AC IOut FIND mag(I(R1)) AT 10

This cannot be solved and the error message is:

Byte sequence 0xb0292061742031300d0a0a0a446174653a204d6f6e204a756c2031392032313a35323a313220323032310a546f74616c20656c61707365642074696d653a20302e343439207365636f6e64732e0a0a746e6f6d203d2032370a74656d70203d2032 is invalid in source encoding or cannot be represented in target encoding
in top-level scope at LTSpiceJL_Test.jl:5
in  at LTspice\YKMNe\src\LTspiceSimulation.jl:361
in measurementvalues at LTspice\YKMNe\src\LTspiceSimulation.jl:153 
in run! at LTspice\YKMNe\src\LTspiceSimulation.jl:406 
in run! at LTspice\YKMNe\src\LTspiceSimulation.jl:417
in parselog! at LTspice\YKMNe\src\ParseLogFile.jl:160
in open at base\io.jl:323
....

**Comment by cstook** [comment]
Hi EliMattingly22,

LTspice.jl only supports .tran simulations for now.  The error you provided does not seem to be related to this.

I wrote this module years ago, mostly as an excuse to learn some Julia.  The code and documentation need some serious clean up at this point, which I intend to do eventually.  It's good to see interest in the project.  It helps motivate me to the work I need to do to fix this module.
